# -*- coding: utf-8 -*-
"""Human Gait Recognition System using Data Analytics & Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n25yshd1mUnl1QfJh_y-OyTTjmtwoodm
"""

!pip install pandas numpy matplotlib seaborn scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data = {
    'step_length': [50,55,60,62,65,70,72,75,80,85],
    'stride_width': [20,21,22,23,24,25,26,27,28,29],
    'walking_speed': [3,3.2,3.5,3.8,4,4.2,4.5,4.8,5,5.2],
    'body_angle': [10,11,12,13,14,15,16,17,18,19],
    'person_id': [0,0,0,0,1,1,1,1,2,2]
}

df = pd.DataFrame(data)

print(df)

print(df.info())

print(df.describe())

plt.hist(df['walking_speed'], bins=5, color='blue')

plt.title("Walking Speed Distribution")
plt.xlabel("Walking Speed")
plt.ylabel("Frequency")

plt.show()

plt.scatter(df['step_length'], df['walking_speed'], color='red')

plt.title("Step Length vs Walking Speed")
plt.xlabel("Step Length")
plt.ylabel("Walking Speed")

plt.show()

sns.heatmap(df.corr(), annot=True)

plt.title("Feature Correlation Heatmap")

plt.show()

X = df[['step_length', 'stride_width', 'walking_speed', 'body_angle']]
y = df['person_id']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

model = RandomForestClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, cmap='Blues')

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

new_person = [[68, 24, 4.1, 14]]

prediction = model.predict(new_person)

print("Predicted Person ID:", prediction[0])